language: ruby

before_install:
  - 'test Node = "$PACPROXY_RUNTIME" && sudo apt-get update'
  - 'test Node = "$PACPROXY_RUNTIME" && sudo apt-get install node'
  - 'test Node = "$PACPROXY_RUNTIME" && (cd lib/pacproxy/runtimes/node ; npm install)'

rvm:
  - 2.0.0
  - 2.1.3

env:
  - PACPROXY_RUNTIME=Node
  - PACPROXY_RUNTIME=
